services:
  jogo-da-velha-websocket:
    build:
      context: .
    container_name: jogo-da-velha-websocket
    restart: unless-stopped
    environment:
      PORT: 3000
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.middlewares.jogo-da-velha-https.redirectscheme.scheme=https"
      - "traefik.http.routers.jogo-da-velha-http.rule=Host(`jogo-da-velha.adoroautomacao.com.br`)"
      - "traefik.http.routers.jogo-da-velha-http.entrypoints=http"
      - "traefik.http.routers.jogo-da-velha-http.middlewares=jogo-da-velha-https"
      - "traefik.http.routers.jogo-da-velha-http.service=jogo-da-velha-svc"
      - "traefik.http.routers.jogo-da-velha.rule=Host(`jogo-da-velha.adoroautomacao.com.br`)"
      - "traefik.http.routers.jogo-da-velha.entrypoints=https"
      - "traefik.http.routers.jogo-da-velha.tls=true"
      - "traefik.http.routers.jogo-da-velha.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jogo-da-velha.priority=20000"
      - "traefik.http.routers.jogo-da-velha.service=jogo-da-velha-svc"
      - "traefik.http.services.jogo-da-velha-svc.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true
